SuazoXD/ProyectoIndustria

Backend/Domain/Entities/Product.cs

feature:se agrego entities y dentro de el se creo Product

feature:se agrego entities y dentro de el se creo Product

---

Backend/Aplication/DTOs/ProductDto.cs
Backend/Aplication/Interfaces/IProductRepository.cs
Backend/Aplication/Interfaces/IProductService.cs
Backend/Aplication/Services/ProductService.cs

feature:se creo dtoproduct y la interface de idproduct y productservice

feature:se creo dtoproduct y la interface de idproduct y productservice

---

.github/workflows/deploy.yml

feature: se agrego deploy

---

Backend/API/Dockerfile

feature: se agrego Dockerfile

---

Backend/Domain/Domain.csproj
Backend/Domain/Entities/Permiso.cs

Feature: Se agrego permiso

---

Backend/Domain/Common/AggregateRoot.cs
Backend/Domain/Common/Entity.cs

Se creo la carpeta common que tiene las clases Entity y AggregateRoot

feature: se acabada de crear la carpeta common

---

Backend/Domain/Entities/ListaDeReproduccion.cs

se agrego ListaDeReproduccion al domain

feature:se agrego ListaDeReproduccion al domain

---

Backend/Domain/Entities/Pago.cs

feature: se creo pago.cs

---

Backend/Domain/Entities/MetodoPago.cs

feature: se cro MetodoPago.cs

---

Backend/Domain/Entities/Archivo.cs
Backend/Domain/Entities/ArchivoListaReproduccion.cs

Se han creado las entidades Archivo y ArchivoListaReproduccion

feature: se han agregado las clases Archivo y ArchivoLR

---

Backend/Domain/Entities/Privacidad.cs

feature: Privacidad

---

Backend/Domain/Entities/Usuario.cs

Feature: Se agrego entity Usuario

Feature: Se agrego entity Usuario

---

Backend/Domain/Entities/Rol.cs

feature: se ha agregado la entidad Rol

feature: se ha agregado la entidad

---

Backend/Domain/Entities/ContenidoPremium.cs
Backend/Domain/Entities/Credito.cs

Se han agregado las clases Credito y ContenidoPremium

feature: agregando las entidades Credito y ContenidoPremium

---

Backend/Infrastructure/Repositories/FacturaRepository.cs

se creo facturaRepository dentro de la carpeta repositories

se creo facturaRepository dentro de la carpeta repositories

---

Backend/Infrastructure/FavoritoRepository.cs
Backend/Infrastructure/Infrastructure.csproj

se agrego FavoritoRepository.cs en repositories

feature: se agrego FavoritoRepository.cs en repositories

---

Backend/Infrastructure/Repositories/PagoRepository.cs

se agrego PagoRepository.cs a repositories

feaure: se agrego PagoRepository.cs a repositories

---

Backend/Infrastructure/Repositories/ArchivoListaReproduccionRepository.cs
Backend/Infrastructure/Repositories/ArchivoRepository.cs

Se ha creado el repositorio para las entidades Archivo y ArchivoListaReproduccion

feature: Se ha agregado el repositorio para Archivo y ArchivoLR

---

Backend/Infrastructure/Repositories/ContenidoPremiumRepository.cs
Backend/Infrastructure/Repositories/CreditoRepository.cs

Se ha creado el repositorio para las entidades ContenidoPremium y Credito

feature: se ha creado el repositorio de ContenidoP y Credito

---

Backend/Aplication/DTOs/Factura/FacturaRequestDTO.cs

feature: se creo el dto de factura

---

Backend/Infrastructure/Repositories/PermisoRepository.cs

Feature: Se agrego el PermisoRepository

Feature: Se agrego el PermisoRepository

---

Backend/Infrastructure/Repositories/PrivacidadRepository.cs

Feature: se agrego PrivacidadRepository

Feature: se agrego PrivacidadRepository

---

Backend/Infrastructure/Repositories/RolRepository.cs

Feature: se agrego RolRepository

Feature: se agrego RolRepository

---

Backend/Aplication/Aplication.csproj
Backend/Aplication/DTOs/Factura/FacturaResponseDTO.cs

 feature: se creo FacturaResponseDTO.cs

---

Backend/Aplication/DTOs/Favorito/FavoritoRequestDTO.cs
Backend/Aplication/DTOs/Favorito/FavoritoResponseDTO.cs

feature: se agrego FavoritoRequestDTO.cs y FavoritRequestDTO.cs

feature: se agrego FavoritoRequestDTO.cs y FavoritRequestDTO.cs

---

Backend/Aplication/DTOs/ListaDeReproduccion/ListaDeReproduccionRequestDTO.cs
Backend/Aplication/DTOs/ListaDeReproduccion/ListaDeReproduccionResponseDTO.cs

feature: se agrego listadereprosuccion response y request

feature: se agrego listadereprosuccion response y request

---

Backend/Aplication/DTOs/MetodoPago/MetodoPagoRequestDTO.cs
Backend/Aplication/DTOs/MetodoPago/MetodoPagoResponseDTO.cs

feature:se creo el response y request del dto de metodopago

feature:se creo el response y request del dto de metodopago

---

Backend/Aplication/DTOs/Pago/PagoRequestDTO.cs
Backend/Aplication/DTOs/Pago/PagoResponseDTO.cs

feature se agrego request y response dto de pago

feature se agrego request y response dto de pago

---

Backend/Infrastructure/DependencyInjection.cs

Feature: Se agrego DependencyInjection

Feature: Se agrego DependencyInjection

---

Backend/Aplication/DTOs/Permiso/PermisoRequestDTO.cs
Backend/Aplication/DTOs/Permiso/PermisoResponseDTO.cs

Festure: se adgregado las clases para PermisoDTO

Festure: se adgregado las clases para PermisoDTO

---

Backend/Infrastructure/DependencyInjection.cs
Backend/Infrastructure/Repositories/Permisos/PermisoRepository.cs
Backend/Infrastructure/Repositories/Privacidades/PrivacidadRepository.cs
Backend/Infrastructure/Repositories/Roles/RolRepository.cs
Backend/Infrastructure/Repositories/Usuarios/UsuarioRepository.cs

has been moved class permisos, usuarios, privacidades,roles

ADD FIX: Infrastructure

---

Backend/Infrastructure/DependencyInjection.cs
Backend/Infrastructure/Repositories/Facturas/FacturaRepository.cs
Backend/Infrastructure/Repositories/Favoritos/FavoritoRepository.cs
Backend/Infrastructure/Repositories/ListaDeReproduccion/ListaDeReproduccionRepository.cs
Backend/Infrastructure/Repositories/MetodoPago/MetodoPagoRepository.cs
Backend/Infrastructure/Repositories/Pagos/PagoRepository.cs

ADD FIX: Infrastructure Repositry

ADD FIX: Infrastructure Repositry

---

Backend/Aplication/Interfaces/Facturas/IFacturaRepository.cs
Backend/Aplication/Interfaces/Facturas/IFacturaService.cs

ADD FEATURE: interface factura interface

ADD FEATURE: interface factura interface

---

Backend/Aplication/DTOs/Permisos/PermisoRequestDTO.cs
Backend/Aplication/DTOs/Permisos/PermisoResponseDTO.cs
Backend/Aplication/DTOs/Privacidades/PrivacidadRequestDTO.cs
Backend/Aplication/DTOs/Privacidades/PrivacidadResponseDTO.cs
Backend/Aplication/DTOs/Roles/RolRequestDTO.cs
Backend/Aplication/DTOs/Roles/RolResponseDTO.cs
Backend/Aplication/DTOs/Usuarios/UsuarioRequestDTO.cs
Backend/Aplication/DTOs/Usuarios/UsuarioResponseDTO.cs

- has been added PrivacidadDTO
- has been added RolDTO
- has been added UsuariosDTO

ADD FEATURE: Aplication DTOs

---

Backend/Aplication/DTOs/Archivos/ArchivoRequestDTO.cs
Backend/Aplication/DTOs/Archivos/ArchivoResponseDTO.cs
Backend/Aplication/DTOs/ArchivosListaReproduccion/ArchivoListaReproduccionRequestDTO.cs
Backend/Aplication/DTOs/ArchivosListaReproduccion/ArchivoListaReproduccionResponseDTO.cs

has been added ArchivoRequestDTO, ArchivoResponseDTO, ArchivoListaReproduccionRequestDTO, ArchivoListaReproduccionResponseDTO

ADD FEATURE: Aplication DTOs Archivo y ArchivoLR

---

Backend/Aplication/DTOs/Archivos/ArchivoRequestDTO.cs
Backend/Aplication/DTOs/Archivos/ArchivoResponseDTO.cs
Backend/Aplication/DTOs/ArchivosListaReproduccion/ArchivoListaReproduccionRequestDTO.cs
Backend/Aplication/DTOs/ArchivosListaReproduccion/ArchivoListaReproduccionResponseDTO.cs
Backend/Aplication/DTOs/ContenidosPremium/ContenidoPremiumRequestDTO.cs
Backend/Aplication/DTOs/ContenidosPremium/ContenidoPremiumResponseDTO.cs
Backend/Aplication/DTOs/Creditos/CreditoRequestDTO.cs
Backend/Aplication/DTOs/Creditos/CreditoResponseDTO.cs

has been added ContenidoPremiumRequestDTO, ContenidoPremiumResponseDTO, CreditoRequestDTO, CreditoResponseDTO

ADD FEATURE: Aplication DTOs ContenidoPremium y Credito

---

Backend/Aplication/Aplication.csproj
Backend/Aplication/Interfaces/Permisos/IPermisoRepository.cs
Backend/Aplication/Interfaces/Permisos/IPermisoService.cs
Backend/Aplication/Interfaces/Privacidades/IPrivacidadRepository.cs
Backend/Aplication/Interfaces/Privacidades/IPrivacidadService.cs

has been added Aplication Interfaces Permisos, Privacidades

ADD FEATURE: Aplication Interfaces Permisos, Privacidades

---

Backend/Aplication/Interfaces/ListaDeReproduccion/IListaDeReproduccionRepository.cs
Backend/Aplication/Interfaces/ListaDeReproduccion/IListaDeReproduccionService.cs

ADD FEATURE: Interfaces ListaDeReproduccion

ADD FEATURE: Interfaces ListaDeReproduccion

---

Backend/Aplication/Interfaces/MetodoPago/IMetodoPagoRepository.cs
Backend/Aplication/Interfaces/MetodoPago/IMetodoPagoService.cs

ADD FEATURE: Interface MetodoPago

ADD FEATURE: Interface MetodoPago

---

Backend/Aplication/Interfaces/Pagos/IPagoRepository.cs
Backend/Aplication/Interfaces/Pagos/IPagoService.cs

ADD FEATURE: inteface Pago

---

Backend/Aplication/DTOs/Roles/RolRequestDTO.cs
Backend/Aplication/DTOs/Roles/RolResponseDTO.cs
Backend/Aplication/DTOs/Usuarios/UsuarioRequestDTO.cs
Backend/Aplication/DTOs/Usuarios/UsuarioResponseDTO.cs
Backend/Aplication/Interfaces/Privacidades/IPrivacidadRepository.cs
Backend/Aplication/Interfaces/Privacidades/IPrivacidadService.cs
Backend/Aplication/Interfaces/Roles/IRolRepository.cs
Backend/Aplication/Interfaces/Roles/IRolService.cs
Backend/Aplication/Interfaces/Usuarios/IUsuarioRepository.cs
Backend/Aplication/Interfaces/Usuarios/IUsuarioService.cs

ADD FEATURE: Interface Roles and User

ADD FEATURE: Interface Roles and User

---

Backend/Aplication/Interfaces/Archivos/IArchivoRepository.cs
Backend/Aplication/Interfaces/Archivos/IArchivoService.cs
Backend/Aplication/Interfaces/ArchivosListaReproduccion/IArchivoListaReproduccionRepository.cs
Backend/Aplication/Interfaces/ArchivosListaReproduccion/IArchivoListaReproduccionService.cs

has been added IArchivoRepository, IArchivoService, IArchivoListaReproduccionService, IArchivoListaReproduccionRepository

ADD FEATURE: Aplication Interfaces Archivo y ArchivoLR

---

Backend/Aplication/Services/Facturas/FacturaService.cs
Backend/Aplication/Services/Favoritos/FavoritoService.cs
Backend/Aplication/Services/ListaDeReproduccion/ListaDeReproduccionService.cs
Backend/Aplication/Services/MetdoPago/MetodoPagoService.cs
Backend/Aplication/Services/Pagos/PagoService.cs

ADD FEATURE:services

---

Backend/Aplication/Interfaces/ContenidosPremium/IContenidoPremiumRepository.cs
Backend/Aplication/Interfaces/ContenidosPremium/IContenidoPremiumService.cs
Backend/Aplication/Interfaces/Creditos/ICreditoRepository.cs
Backend/Aplication/Interfaces/Creditos/ICreditoService.cs

has been added ICreditoRepository, ICreditoService, IContenidoPremiumRepository, IContenidoPremiumService

ADD FEATURE: Aplication Interfaces ContenidoPremium y Credito

---

Backend/Aplication/Aplication.csproj
Backend/Aplication/Services/Archivos/ArchivoService.cs
Backend/Aplication/Services/ArchivosListaReproduccion/ArchivoListaReproduccionService.cs
Backend/Aplication/Services/ContenidosPremium/ContenidoPremiumService.cs
Backend/Aplication/Services/Creditos/CreditoService.cs

has been added ArchivoService, ArchivoListaReproduccionService, ContenidoPremiumService, CreditoService

ADD FEATURE: Aplication Services Archivo, ArchivoLR, ContenidoP, Credito

---

Backend/Aplication/Interfaces/ContenidosPremium/IContenidoPremiumRepository.cs

has been modificated IContenidoPremiumRepository

 ADD FIX: Aplication Interfaces ContenidoPremium

---

Backend/API/Configuration/DBConnections.cs
Backend/API/appsettings.json

ADD API:DBConnections

---

Backend/Aplication/Interfaces/Pagos/IPagoRepository.cs
Backend/Aplication/Interfaces/Roles/IRolRepository.cs
Backend/Aplication/Interfaces/Usuarios/IUsuarioRepository.cs
Backend/Aplication/Services/Pagos/PagoService.cs
Backend/Aplication/Services/Roles/RolService.cs
Backend/Aplication/Services/Usuarios/UsuarioService.cs
Backend/Domain/Entities/ContenidoPremium.cs
Backend/Domain/Entities/Credito.cs
Backend/Domain/Entities/Factura.cs
Backend/Domain/Entities/Favorito.cs
Backend/Domain/Entities/MetodoPago.cs
Backend/Domain/Entities/Pago.cs
Backend/Domain/Entities/Permiso.cs
Backend/Domain/Entities/Privacidad.cs
Backend/Domain/Entities/Rol.cs
Backend/Domain/Entities/Usuario.cs
Backend/Infrastructure/Repositories/Pagos/PagoRepository.cs
Backend/Infrastructure/Repositories/Roles/RolRepository.cs
Backend/Infrastructure/Repositories/Usuarios/UsuarioRepository.cs

has been moved Usuario, Rol, Pago to Entities

ADD FIX: Domain AggregateRoot

---

.github/workflows/deploy.yml

Fix Update deploy

---

Backend/API/Configuration/DBConnections.cs
Backend/API/Configuration/JwtSettings.cs
Backend/API/Program.cs
Backend/API/appsettings.json

ADD FEATURE KEY

---

Backend/API/API.csproj
Backend/API/Configuration/JwtSettings.cs
Backend/API/Controllers/AccesoController.cs
Backend/API/Custom/Utilidades.cs
Backend/API/Program.cs
Backend/API/appsettings.json

ADD FETURE: UTILIDADES|CORS|JWT|ACCESO_CONTROLLER

ADD FETURE: UTILIDADES|CORS|JWT|ACCESO_CONTROLLER

---

Backend/API/Controllers/ArchivoController.cs
Backend/API/Controllers/ArchivoListaReproduccionController.cs

has been added ArchivoController and ArchivoListaReproduccionController

ADD FEATURE: API Controller Archivo and ArchivoListaReproduccion

---

Backend/API/Controllers/ContenidoPremiumController.cs
Backend/API/Controllers/CreditoController.cs

has been added ContenidoPremiumController and CreditoController

ADD FEATURE: API Controller ContenidoPremium and Credito

---

Backend/API/Controllers/LoginController.cs

has been added LoginController

ADD FEATURE: API Controller LoginController

---

Backend/API/Controllers/FacturaController.cs
Backend/API/Controllers/FavoritoController.cs
Backend/API/Controllers/ListaDeReproduccionController.cs
Backend/API/Controllers/MetodoPagoController.cs
Backend/API/Controllers/PagoController.cs

ADD FEATURE:API CONTROLLER

---

Backend/API/Program.cs

Fix: Program

---

Backend/API/Controllers/ArchivoController.cs
Backend/Aplication/Interfaces/Archivos/IArchivoService.cs

FIX: Archivo

---

Backend/API/Controllers/RolController.cs

Fix: RolController

---

Backend/API/Controllers/ListaDeReproduccionController.cs
Backend/Aplication/Interfaces/ListaDeReproduccion/IListaDeReproduccionService.cs
Backend/Aplication/Services/ListaDeReproduccion/ListaDeReproduccionService.cs

has been modificated ListaDeReproduccionService/Controller/Interface

ADD FIX: ListaDeReproduccion

---

Backend/API/Controllers/FavoritoController.cs
Backend/Aplication/Interfaces/Favoritos/IFavoritoRepository.cs
Backend/Aplication/Interfaces/Favoritos/IFavoritoService.cs
Backend/Aplication/Services/Favoritos/FavoritoService.cs
Backend/Infrastructure/Repositories/Favoritos/FavoritoRepository.cs

Fix: Favorite

---

Backend/API/Controllers/CreditoController.cs
Backend/Aplication/Interfaces/Creditos/ICreditoService.cs
Backend/Aplication/Services/Creditos/CreditoService.cs
Backend/Infrastructure/Repositories/Creditos/CreditoRepository.cs

has been modificated CreditoService/Controller/Repositories/Interface

ADD FIX: Credito

---

Backend/API/Controllers/PrivacidadController.cs
Backend/Aplication/Interfaces/Privacidades/IPrivacidadRepository.cs
Backend/Aplication/Interfaces/Privacidades/IPrivacidadService.cs
Backend/Aplication/Services/Privacidades/PrivacidadService.cs
Backend/Infrastructure/Repositories/Privacidades/PrivacidadRepository.cs

ADD FIX: cambio

---

Backend/API/Controllers/UsuarioController.cs

Fix: UsuarioController
